### ISSUE TITLE
Multibranch timeline view crash in GEMOC xCapella RCP 1.1.0

### ISSUE THREAD

**Issue by dvojtise** [gemoc/xCapella#2]
When running the washingmachine example directly in the GEMOC xCapella RCP 1.1.0, the multibranch timeline sometimes crashes with the following exception:
```
java.lang.NullPointerException
	at org.eclipse.gemoc.timeline.view.AbstractTimelineView.setTimelineProvider(AbstractTimelineView.java:638)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.configure(EventSchedulingTimeLineView.java:151)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.init(EventSchedulingTimeLineView.java:84)
	at org.eclipse.ui.part.ViewPart.init(ViewPart.java:110)
```

Complement: the timeline seems to work in the following situation:
- install all plugin of the xcapella language in the first studio, start a runtime workbench, install and run the washingmachine example in the runtime workbench.
- I also succeed to get it work, by pre-opening the view before the start on the simulation.

**Comment by dvojtise** [comment]
The Timeline View should be opened before launching the simulation.

The real fix should be done in GEMOC itself,

In order to minimize this issue, #3 has been fixed
